name: Bug Report
description: File a bug report
title: "[Title here. keep it short]"
labels: ["bug"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        One second before you create, search if it's already reported [issues](https://github.com/thewh1teagle/kokoro-onnx/issues?q=is:issue+label:bug+)

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see! adding code example won't hurt.
      value: |
        1. step one...
        2. step two...
    validations:
      required: true
  - type: dropdown
    id: platforms
    attributes:
      label: What OS are you seeing the problem on?
      multiple: true
      options:
        - Window
        - Linux
        - MacOS
  - type: input
    id: version
    attributes:
      label: Package version
      description: |
        Run `uv pip show kokoro-onnx` (omit uv if needed)
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.

        You can enable logs by setting LOG_LEVEL=DEBUG environment variable.

        Example (Linux/macOS):
          LOG_LEVEL=DEBUG python main.py

        Example (PowerShell):
          $env:LOG_LEVEL=DEBUG; python main.py

      render: shell
