"""
pip install kokoro-onnx soundfile

wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files/kokoro-v0_19.onnx
wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files/voices.json
python examples/play.py
"""

import sounddevice as sd
from kokoro_onnx import Kokoro

kokoro = Kokoro('kokoro-v0_19.onnx', 'voices.json')
samples, sample_rate = kokoro.create('Hello. This audio generated by kokoro!', voice='af_sarah', speed=1.0, lang='en-us')
print('Playing audio...')
sd.play(samples, sample_rate)
sd.wait()