"""
pip install kokoro-onnx soundfile

wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files/kokoro-v0_19.onnx
wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files/voices.json
python examples/usage.py
"""

import soundfile as sf
from kokoro_onnx import Kokoro

kokoro = Kokoro('kokoro-v0_19.onnx', 'voices.json')
samples, sample_rate = kokoro.create('Hello! This audio generated by kokoro!', 'af_nicole', speed=1.0)
sf.write('audio.wav', samples, sample_rate)