"""
Note: on Linux you need to run this as well: apt-get install portaudio19-dev

pip install kokoro-onnx sounddevice

wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files/kokoro-v0_19.onnx
wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files/voices.json

ESPEAK_NG_LIB_PATH="/usr/local/Cellar/espeak-ng/1.52.0/lib/libespeak-ng.1.dylib" python examples/with_espeak_lib.py
"""

import os
import sounddevice as sd
from kokoro_onnx import Kokoro

kokoro = Kokoro(
    "kokoro-v0_19.onnx",
    "voices.json",
    espeak_ng_lib_path=os.getenv("ESPEAK_NG_LIB_PATH", None))
samples, sample_rate = kokoro.create(
    "Hello. This audio generated by kokoro!", voice="af_sarah", speed=1.0, lang="en-us"
)
print("Playing audio...")
sd.play(samples, sample_rate)
sd.wait()
