"""
Render speech into an mp4 with the whole sentence as subtitles, highlighting the
spoken word on a rounded box, synced by the model timestamps.
Timestamps come from models exported with a duration output, such as the
kokoro-v1.0.onnx from model-files-v1.1 or any model built with scripts/export.py

pip install -U kokoro-onnx soundfile moviepy

wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.1/kokoro-v1.0.onnx
wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.1/voices-v1.0.bin
python examples/with_video_subtitles.py
"""

import bisect

import numpy as np
import soundfile as sf
from moviepy import AudioFileClip, VideoClip
from PIL import Image, ImageDraw, ImageFont

from kokoro_onnx import Kokoro

WIDTH, HEIGHT = 1280, 720
BACKGROUND = (24, 26, 38)
TEXT_COLOR = (150, 155, 175)
SPOKEN_COLOR = (255, 255, 255)
BOX_COLOR = (88, 101, 242)
BOX_PADDING_X, BOX_PADDING_Y, BOX_RADIUS = 6, 12, 14
TRANSITION = 0.15  # seconds the highlight takes to glide onto the next word

kokoro = Kokoro("kokoro-v1.0.onnx", "voices-v1.0.bin")
if not kokoro.has_timings:
    raise SystemExit(
        "This model reports no durations, export one with scripts/export.py"
    )

text = "Hello. This audio generated by kokoro, and the subtitles follow every word!"
samples, sample_rate, timings = kokoro.create_timed(text, voice="af_sarah", lang="en-us")
sf.write("audio.wav", samples, sample_rate)

# One timing per phoneme, so group them into words on the spaces between them,
# then pair each group with the matching word of the text
spans = []
start, end = None, 0.0
for timing in [*timings, None]:
    if timing is not None and timing.phoneme != " ":
        start = timing.start if start is None else start
        end = timing.end
        continue
    if start is not None:
        spans.append((start, end))
    start = None
words = list(zip(text.split(), spans))

# Lay the sentence out once, wrapping into centered lines and keeping each
# word's box so the highlight can be drawn behind the one being spoken
font = ImageFont.load_default(size=56)
measure = ImageDraw.Draw(Image.new("RGB", (1, 1)))
space = measure.textlength(" ", font=font)
ascent, descent = font.getmetrics()
line_height = (ascent + descent) * 1.6

lines, line = [], []
x = 0.0
for word, _ in words:
    width = measure.textlength(word, font=font)
    if line and x + width > WIDTH - 200:
        lines.append(line)
        line, x = [], 0.0
    line.append((word, x, width))
    x += width + space
lines.append(line)

boxes = []
top = (HEIGHT - line_height * len(lines)) / 2
for row, line in enumerate(lines):
    used = line[-1][1] + line[-1][2]
    left = (WIDTH - used) / 2
    for word, x, width in line:
        boxes.append((left + x, top + row * line_height, width))

rects = [
    (
        x - BOX_PADDING_X,
        y - BOX_PADDING_Y,
        x + width + BOX_PADDING_X,
        y + ascent + descent + BOX_PADDING_Y,
    )
    for x, y, width in boxes
]

def lerp(a, b, p):
    return tuple(u + (v - u) * p for u, v in zip(a, b))

# Cap each glide at the gap to the previous word so it always lands before the
# next one begins, otherwise fast words would cut a glide short and jump
starts = [start for _, (start, _) in words]
glides = [
    TRANSITION,
    *(min(TRANSITION, max(b - a, 0.01)) for a, b in zip(starts, starts[1:])),
]

def make_frame(t: float) -> np.ndarray:
    # The highlight holds on each word until the next one starts, then glides
    # over with an ease-out while the word colors crossfade
    spoken = max(bisect.bisect_right(starts, t) - 1, 0)
    progress = 1.0 if spoken == 0 else min((t - starts[spoken]) / glides[spoken], 1.0)
    progress = 1 - (1 - progress) ** 3
    rect = lerp(rects[spoken - 1], rects[spoken], progress)

    image = Image.new("RGB", (WIDTH, HEIGHT), BACKGROUND)
    draw = ImageDraw.Draw(image)
    draw.rounded_rectangle(rect, radius=BOX_RADIUS, fill=BOX_COLOR)
    for i, ((word, _), (x, y, _)) in enumerate(zip(words, boxes)):
        color = TEXT_COLOR
        if i == spoken:
            color = lerp(TEXT_COLOR, SPOKEN_COLOR, progress)
        elif i == spoken - 1:
            color = lerp(SPOKEN_COLOR, TEXT_COLOR, progress)
        draw.text((x, y), word, font=font, fill=tuple(round(c) for c in color))
    return np.asarray(image)

audio = AudioFileClip("audio.wav")
video = VideoClip(make_frame, duration=audio.duration).with_audio(audio)
video.write_videofile("video.mp4", fps=60)
print("Created video.mp4")
