"""
Timestamps come from models exported with a duration output, such as
kokoro-v1.1-zh.onnx or any model built with scripts/export.py. Those models can
also synthesize with continuous=True, see examples/with_continuous.py

pip install -U kokoro-onnx soundfile

wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.1/kokoro-v1.1-zh.onnx
wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.1/voices-v1.1-zh.bin
wget https://huggingface.co/hexgrad/Kokoro-82M-v1.1-zh/raw/main/config.json
python examples/with_timestamps.py
"""

import soundfile as sf

from kokoro_onnx import Kokoro

kokoro = Kokoro("kokoro-v1.1-zh.onnx", "voices-v1.1-zh.bin", vocab_config="config.json")
if not kokoro.has_timings:
    raise SystemExit(
        "This model reports no durations, export one with scripts/export.py"
    )

samples, sample_rate, timings = kokoro.create_timed(
    "Hello. This audio generated by kokoro!", voice="af_maple", lang="en-us"
)
sf.write("audio.wav", samples, sample_rate)
print("Created audio.wav")

# One timing per phoneme, so group them into words on the spaces between them
word, start, end = "", 0.0, 0.0
for timing in [*timings, None]:
    if timing is not None and timing.phoneme != " ":
        start = timing.start if not word else start
        word, end = word + timing.phoneme, timing.end
        continue
    if word:
        print(f"{start:5.2f}s - {end:5.2f}s  {word}")
    word = ""
